---
name: Create Release

on:
  push:
    branches: [embedded]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@4c5670f886fe259db4d11222f7dff41c1382304d # v3.7.12
        with:
          command: manifest
          token: ${{ secrets.AUTOMATIC_RELEASE_PLEASE_TOKEN }}
