name: Update Dependencies

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest
    # Using our own container is required since we need all package sources
    # set-up correctly.
    container: ghcr.io/philips-software/amp-devcontainer-gcc-10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Run update dependencies
        working-directory: .devcontainer
        run: ./update-dependencies.sh base gcc-10
      - uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        with:
          commit-message: "build(deps): update apt-requirements.json"
          branch: feature/update-apt-dependencies
          title: "build(deps): update apt-requirements.json"
          labels: dependencies
          delete-branch: true
